name: Deploy Customer Backend (Multi-Env)

on:
  push:
    branches: ["main", "develop"]
    paths:
      - "apps/customer-backend/**"
      - "packages/**"
      - "Dockerfile"
      - "turbo.json"
      - "pnpm-lock.yaml"

env:
  # Thay bằng username DockerHub của bạn
  IMAGE_NAME: hoanphuc/printz-customer-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Phân loại môi trường: main -> PROD, develop -> STAGING
      - name: Set Environment Metadata
        id: meta
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
            echo "ENV_NAME=production" >> $GITHUB_OUTPUT
          else
            echo "TAG=staging" >> $GITHUB_OUTPUT
            echo "ENV_NAME=staging" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name:QB Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Trỏ đúng file Dockerfile vừa tạo ở trên
          file: apps/customer-backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Trigger PROD (Gọi Hook Prod từ ảnh secrets bạn gửi)
      - name: Trigger Render Deploy (PRODUCTION)
        if: steps.meta.outputs.ENV_NAME == 'production'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_CUSTOMER_PROD }}

      # Trigger STAGING (Gọi Hook Staging từ ảnh secrets bạn gửi)
      - name: Trigger Render Deploy (STAGING)
        if: steps.meta.outputs.ENV_NAME == 'staging'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_CUSTOMER_STAGING }}